version: "3"
services:
  cassandra-dc1-node1:
    image: cassandra:latest
    container_name: cassandra-dc1-node1
    environment:
      - CASSANDRA_CLUSTER_NAME=my_cassandra_cluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_SEEDS=cassandra-dc1-node1,cassandra-dc2-node1
      - CASSANDRA_LISTEN_ADDRESS=cassandra-dc1-node1
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-dc1-node1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    networks:
      - cassandra_network
    volumes:
      - cassandra-data-dc1-node1:/var/lib/cassandra
    ports:
      - "9042:9042"

  cassandra-dc1-node2:
    image: cassandra:latest
    container_name: cassandra-dc1-node2
    environment:
      - CASSANDRA_CLUSTER_NAME=my_cassandra_cluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack2
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_SEEDS=cassandra-dc1-node1,cassandra-dc2-node1
      - CASSANDRA_LISTEN_ADDRESS=cassandra-dc1-node2
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-dc1-node2
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    networks:
      - cassandra_network
    volumes:
      - cassandra-data-dc1-node2:/var/lib/cassandra

  cassandra-dc1-node3:
    image: cassandra:latest
    container_name: cassandra-dc1-node3
    environment:
      - CASSANDRA_CLUSTER_NAME=my_cassandra_cluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack3
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_SEEDS=cassandra-dc1-node1,cassandra-dc2-node1
      - CASSANDRA_LISTEN_ADDRESS=cassandra-dc1-node3
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-dc1-node3
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    networks:
      - cassandra_network
    volumes:
      - cassandra-data-dc1-node3:/var/lib/cassandra

  cassandra-dc2-node1:
    image: cassandra:latest
    container_name: cassandra-dc2-node1
    environment:
      - CASSANDRA_CLUSTER_NAME=my_cassandra_cluster
      - CASSANDRA_DC=dc2
      - CASSANDRA_RACK=rack1
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_SEEDS=cassandra-dc1-node1,cassandra-dc2-node1
      - CASSANDRA_LISTEN_ADDRESS=cassandra-dc2-node1
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-dc2-node1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    networks:
      - cassandra_network
    volumes:
      - cassandra-data-dc2-node1:/var/lib/cassandra

  cassandra-dc2-node2:
    image: cassandra:latest
    container_name: cassandra-dc2-node2
    environment:
      - CASSANDRA_CLUSTER_NAME=my_cassandra_cluster
      - CASSANDRA_DC=dc2
      - CASSANDRA_RACK=rack2
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_SEEDS=cassandra-dc1-node1,cassandra-dc2-node1
      - CASSANDRA_LISTEN_ADDRESS=cassandra-dc2-node2
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-dc2-node2
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    networks:
      - cassandra_network
    volumes:
      - cassandra-data-dc2-node2:/var/lib/cassandra

  cassandra-dc2-node3:
    image: cassandra:latest
    container_name: cassandra-dc2-node3
    environment:
      - CASSANDRA_CLUSTER_NAME=my_cassandra_cluster
      - CASSANDRA_DC=dc2
      - CASSANDRA_RACK=rack3
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_SEEDS=cassandra-dc1-node1,cassandra-dc2-node1
      - CASSANDRA_LISTEN_ADDRESS=cassandra-dc2-node3
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-dc2-node3
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    networks:
      - cassandra_network
    volumes:
      - cassandra-data-dc2-node3:/var/lib/cassandra

  cqlsh:
    image: nuvo/docker-cqlsh:latest
    container_name: cqlsh
    networks:
      - cassandra_network
    entrypoint: ["cqlsh", "cassandra-dc1-node1", "9042", "--cqlversion=3.4.7"]
    depends_on:
      - cassandra-dc1-node1
      - cassandra-dc1-node2
      - cassandra-dc1-node3
      - cassandra-dc2-node1
      - cassandra-dc2-node2
      - cassandra-dc2-node3
    stdin_open: true
    tty: true

networks:
  cassandra_network:
    driver: bridge

volumes:
  cassandra-data-dc1-node1:
  cassandra-data-dc1-node2:
  cassandra-data-dc1-node3:
  cassandra-data-dc2-node1:
  cassandra-data-dc2-node2:
  cassandra-data-dc2-node3:
